twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        'public/images': images
        'public/css': styles

    globals:
        RECAPTCHA_SITE_KEY: '%env(RECAPTCHA_SITE_KEY)%'
        FACEBOOK_APP_ID: '%env(FACEBOOK_APP_ID)%'
