version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaherecode

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'

  nginx:
    image: nginx:1.19.8-alpine
    restart: on-failure
    volumes:
      - './:/usr/src/app'
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
