version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaherecode
    volumes:
      - './.docker/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - kaherecode

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
    networks:
      - kaherecode

  nginx:
    image: nginx:1.19.8-alpine
    restart: on-failure
    volumes:
      - './:/usr/src/app'
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8000:80'
    depends_on:
      - php
    networks:
      - kaherecode

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    env_file:
      - .env.local
    networks:
      - kaherecode

networks:
  kaherecode:
