version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaherecode
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - kaherecode

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - kaherecode

  nginx:
    image: nginx:1.19.8-alpine
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - php
    networks:
      - kaherecode

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    env_file:
      - .env.local
    networks:
      - kaherecode

  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    command: yarn encore dev --watch
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    restart: on-failure
    networks:
      - kaherecode

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - cluster.name=kaherecode-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    restart: on-failure
    networks:
      - kaherecode

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: on-failure
    networks:
      - kaherecode

networks:
  kaherecode:
