version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: kaherecode_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD:

      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip pdo_mysql xsl

      # restore composer cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer update && composer install -n --prefer-dist

      # save composer cache
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Setup Database"
          command: |
            php bin/console doctrine:database:create --env=test
            php bin/console doctrine:migrations:migrate --env=test
            php bin/console doctrine:fixtures:load -n --env=test

      # restore yarn cache
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-

      - run:
          name: "Install JS Dependencies"
          command: yarn install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: "Build assets"
          command: yarn run encore production

      # run tests with phpunit
      - run:
          name: "Run tests"
          command: composer tests
